import { defineConfig } from 'vitest/config'
import tsconfigPaths from 'vite-tsconfig-paths'

export default defineConfig({
  plugins: [tsconfigPaths()],
  test: {
    environment: 'node',
    globals: true,
    include: [
      'scripts/ui-catalog-source.test.mjs',
      'lib/property-setup.test.ts',
      'lib/vendor-reminders.test.ts',
      'lib/deployment-config.test.ts',
      'lib/daily-csv-export.test.ts',
      'lib/android-webview.test.ts',
      'lib/billing-plans.test.ts',
      'lib/subscription-checkout.test.ts',
      'lib/subscription-reconciliation.test.ts',
      'lib/csv-tools.test.ts',
      'lib/work-order-state.test.ts',
      'lib/workflow-rules.test.ts',
      'lib/request-guidance.test.ts',
      'lib/next-action-engine.test.ts',
      'lib/request-scheduling.test.ts',
      'lib/onboarding.test.ts',
      'lib/portal-auth-delivery.test.ts',
      'lib/portal-subscription-access.test.ts',
      'lib/today-overview.test.ts',
      'lib/request-closeout-language.test.ts',
      'lib/tenant-request-language.test.ts',
      'lib/tenant-effective-status.test.ts',
      'lib/unit-billing-summary.test.ts',
      'lib/vendor-request-state.test.ts',
      'lib/appointment-time.test.ts',
      'lib/notify.test.ts',
      'lib/inspection-templates.test.ts',
      'lib/inspection-completion.test.ts',
      'lib/inspection-report.test.ts',
      'lib/unit-turn-templates.test.ts',
      'lib/maintenance-calendar.test.ts',
      'lib/outlook-calendar-sync.test.ts',
      'lib/mailbox-providers.test.ts',
      'lib/staff-workflow.test.ts',
      'lib/staff-assignment.test.ts',
      'lib/personal-work.test.ts',
      'lib/scheduling-coordination.test.ts',
      'lib/quickbooks.test.ts',
      'lib/subscription-unit-pricing.test.ts',
      'lib/localization.test.ts',
      'lib/localization-entitlement.test.ts',
      'lib/comment-localization.test.ts',
      'lib/translation.test.ts',
      'lib/operator-alerts.test.ts',
      'lib/runtime-env.test.ts',
      'lib/production-safety.test.ts',
      'lib/feature-switches.test.ts',
      'lib/external-operations.test.ts',
      'lib/sentry-reporting.test.ts',
      'lib/financial-idempotency-source.test.ts',
      'lib/appointment-date-time-fields-source.test.ts',
      'app/maintenance/auth/login/actions.test.ts',
      'app/api/monitoring/client-error/route.test.ts',
    ],
  },
})
