import Link from 'next/link'
import { redirect } from 'next/navigation'
import { prisma } from '@/lib/prisma'
import { getLandlordSession } from '@/lib/landlord-session'
import { saveSchedulingPreferencesAction } from './actions'

export default async function SchedulingPreferencesPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const session = await getLandlordSession(); if (!session) redirect('/login?error=session-expired')
  const [account, query] = await Promise.all([prisma.user.findUniqueOrThrow({ where: { id: session.userId } }), searchParams])
  return <div className="stack"><div><Link href="/calendar">Maintenance calendar</Link><h1>Scheduling coordination</h1><p className="muted">Let assigned vendors or staff offer times directly to tenants within your rules.</p></div>{query.saved ? <div className="notice success">Scheduling preferences saved.</div> : null}{query.error ? <div className="notice error">{query.error}</div> : null}<form action={saveSchedulingPreferencesAction} className="card stack"><label className="row"><input type="checkbox" name="enabled" defaultChecked={account.schedulingCoordinationEnabled} /> Enable direct scheduling for new and existing tickets</label><label className="row"><input type="checkbox" name="autoConfirm" defaultChecked={account.schedulingAutoConfirmEnabled} /> Confirm the appointment automatically when the tenant accepts</label><div className="grid cols-2"><label>Working day starts<select name="workingHourStart" defaultValue={account.schedulingWorkingHourStart}>{Array.from({ length: 24 }, (_, hour) => <option value={hour} key={hour}>{String(hour).padStart(2, '0')}:00</option>)}</select></label><label>Working day ends<select name="workingHourEnd" defaultValue={account.schedulingWorkingHourEnd}>{Array.from({ length: 24 }, (_, index) => index + 1).map((hour) => <option value={hour} key={hour}>{String(hour).padStart(2, '0')}:00</option>)}</select></label><label>Minimum notice (hours)<input type="number" name="minimumNoticeHours" min="0" max="336" defaultValue={account.schedulingMinimumNoticeHours} /></label><label>Default appointment length (minutes)<input type="number" name="defaultDurationMinutes" min="15" max="480" step="15" defaultValue={account.schedulingDefaultDurationMinutes} /></label><label>Tenant response window (hours)<input type="number" name="proposalExpiryHours" min="1" max="168" defaultValue={account.schedulingProposalExpiryHours} /></label></div><button className="button primary">Save scheduling preferences</button></form><section className="card stack"><h2>How confirmation works</h2><p>Only assigned vendors or staff can offer up to three times. The tenant chooses one. Unselected times close automatically, and the confirmed time is added to the maintenance calendar and Outlook sync.</p></section></div>
}
