import Link from 'next/link'
import { notFound } from 'next/navigation'
import { requireStaffSession } from '@/lib/staff-auth'
import { prisma } from '@/lib/prisma'
import { formatAppointmentWindow } from '@/lib/appointment-time'
import { formatDateTime } from '@/lib/ui-utils'
import { saveStaffWorkUpdateAction } from '../../actions'
import { AppointmentCoordinationPanel } from '@/components/appointment-coordination-panel'
import { localizeRequestText } from '@/lib/request-text-localization'
import { TranslatedMessage } from '@/components/translated-message'
import { signOutStaffAction } from '../../signout/actions'

export default async function StaffRequestPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ saved?: string; error?: string; schedulingError?: string; slots?: string; appointment?: string }> }) {
  const session = await requireStaffSession(); const [{ id }, query] = await Promise.all([params, searchParams])
  const rawRequest = await prisma.maintenanceRequest.findFirst({ where: { id, assignedStaffId: session.staffMemberId, property: { ownerId: session.orgId } }, include: { property: true, unit: true, staffWorkLogs: { where: { staffMemberId: session.staffMemberId }, orderBy: { createdAt: 'desc' } } } })
  if (!rawRequest) notFound()
  const request = { ...rawRequest, ...await localizeRequestText({ title: rawRequest.title, description: rawRequest.description, sourceLanguage: rawRequest.preferredLanguage, targetLanguage: session.localizationEnabled ? session.preferredLanguage ?? 'english' : 'english' }) }
  return <div className="stack"><div className="row" style={{ alignItems: 'flex-start' }}><div><Link href="/maintenance">Assigned work</Link><h1>{request.title}</h1>{request.isTitleTranslated ? <details className="messageOriginal"><summary>View original title</summary><div data-no-localize>{request.originalTitle}</div></details> : null}<p className="muted">{request.property.name} - {request.unit.label} - {request.urgency} urgency</p></div><form action={signOutStaffAction}><button className="button">Sign out</button></form></div>
    {query.saved ? <div className="notice success">Work update saved.</div> : null}{query.error ? <div className="notice error">{query.error}</div> : null}{query.schedulingError ? <div className="notice error">{query.schedulingError}</div> : null}{query.slots === 'offered' ? <div className="notice success">Appointment choices sent to the tenant.</div> : null}{query.appointment === 'canceled' ? <div className="notice success">Appointment canceled. Offer replacement times below.</div> : null}
    <section className="card stack"><h2>Work order</h2><div><strong>Description</strong><TranslatedMessage body={request.description} originalBody={request.originalDescription} isTranslated={request.isDescriptionTranslated} /></div>{request.submittedByName ? <div><strong>Resident</strong><div className="muted">{request.submittedByName}{request.submittedByEmail ? ` - ${request.submittedByEmail}` : ''}</div></div> : null}{request.staffScheduledStart ? <div><strong>Appointment</strong><div>{formatAppointmentWindow(request.staffScheduledStart, request.staffScheduledEnd)}</div></div> : null}</section>
    <AppointmentCoordinationPanel requestId={request.id} audience="staff" />
    {!['closed', 'canceled'].includes(request.status) ? <form action={saveStaffWorkUpdateAction} encType="multipart/form-data" className="card stack"><input type="hidden" name="requestId" value={request.id} /><h2>Work update</h2><label>Status<select name="status" defaultValue={request.staffWorkStatus ?? 'accepted'}><option value="accepted">Accepted</option><option value="declined">Decline assignment</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="completed">Completed</option></select></label><div className="grid cols-2"><label>Appointment start<input type="datetime-local" name="scheduledStart" /></label><label>Appointment end<input type="datetime-local" name="scheduledEnd" /></label></div><div className="grid cols-2"><label>Labor hours<input type="number" name="laborHours" min="0" max="24" step="0.25" defaultValue="0" /></label><label>Materials used ($)<input type="number" name="materialsAmount" min="0" max="100000" step="0.01" defaultValue="0" /></label></div><label>Notes<textarea name="note" rows={4} /></label><label>Work photo<input type="file" name="photo" accept="image/*" /></label><button className="button primary">Save work update</button></form> : null}
    <section className="card stack"><h2>Work history</h2>{request.staffWorkLogs.length ? request.staffWorkLogs.map((log) => <div className="timelineRow" key={log.id}><div className="row"><strong>{log.status.replaceAll('_', ' ')}</strong><span className="muted">{formatDateTime(log.createdAt)}</span></div><div>{log.laborMinutes} minutes - materials ${(log.materialsCents / 100).toFixed(2)}</div>{log.note ? <div>{log.note}</div> : null}{log.photoUrl ? <a href={`/api/maintenance/media/${log.id}`} target="_blank" rel="noreferrer">View work photo</a> : null}</div>) : <div className="muted">No staff updates yet.</div>}</section>
  </div>
}
