ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "sizeSqFt" INTEGER;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "bedrooms" INTEGER;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "bathrooms" DOUBLE PRECISION;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "monthlyRentCents" INTEGER;
