import Link from 'next/link'
import { redirect } from 'next/navigation'
import { saveTurnBoardPreferencesAction, saveUnitTurnTemplateAction } from '@/app/turns/actions'
import { getLandlordSession } from '@/lib/landlord-session'
import { prisma } from '@/lib/prisma'
import { decodeUnitTurnTasks, ensureDefaultUnitTurnTemplate, serializeUnitTurnTasks } from '@/lib/unit-turn-templates'

function Fields({ template }: { template?: { id: string; name: string; tasksJson: string; defaultTargetDays: number; requirePhotoForCompletion: boolean; requireNoteForCompletion: boolean; requireAllTasksForReady: boolean } }) { return <>{template ? <input type="hidden" name="templateId" value={template.id} /> : null}<label>Template name<input required name="name" defaultValue={template?.name} /></label><label>Tasks <span className="muted">One per line: task | expected days | manager or vendor</span><textarea required rows={10} name="tasks" defaultValue={template ? serializeUnitTurnTasks(decodeUnitTurnTasks(template.tasksJson)) : 'First task | 1 | manager'} /></label><label>Default target days<input type="number" min="1" max="180" required name="defaultTargetDays" defaultValue={template?.defaultTargetDays ?? 10} /></label><label className="row"><input type="checkbox" name="requirePhotoForCompletion" defaultChecked={template?.requirePhotoForCompletion} /> Require a completion photo for every task</label><label className="row"><input type="checkbox" name="requireNoteForCompletion" defaultChecked={template?.requireNoteForCompletion} /> Require a completion note for every task</label><label className="row"><input type="checkbox" name="requireAllTasksForReady" defaultChecked={template?.requireAllTasksForReady ?? true} /> Require all tasks before ready approval</label><button className="button primary" type="submit">Save preferences</button></> }

export default async function TurnPreferencesPage({ searchParams }: { searchParams: Promise<{ saved?: string; viewSaved?: string; error?: string }> }) {
  const session = await getLandlordSession(); if (!session) redirect('/login?error=session-expired'); await ensureDefaultUnitTurnTemplate(session.userId)
  const [templates, properties, user, query] = await Promise.all([prisma.unitTurnTemplate.findMany({ where: { orgId: session.userId }, orderBy: { name: 'asc' } }), prisma.property.findMany({ where: { ownerId: session.userId, isActive: true }, orderBy: { name: 'asc' } }), prisma.user.findUniqueOrThrow({ where: { id: session.userId } }), searchParams])
  return <div className="stack"><div><Link href="/turns">Unit turns</Link><h1>Unit turn preferences</h1><p className="muted">Save the process once, then adjust individual tasks when a turn needs something different.</p></div>{query.saved ? <div className="notice success">Turn template saved.</div> : null}{query.viewSaved ? <div className="notice success">Default board view saved.</div> : null}{query.error ? <div className="notice error">{query.error}</div> : null}
    <form action={saveTurnBoardPreferencesAction} className="card stack"><h2>Saved board view</h2><div className="grid cols-2"><label>Default status<select name="status" defaultValue={user.turnBoardStatusFilter}><option value="active">Active</option><option value="planned">Planned</option><option value="in_progress">In progress</option><option value="ready">Ready</option><option value="all">All</option></select></label><label>Default property<select name="propertyId" defaultValue={user.turnBoardPropertyFilter ?? ''}><option value="">All properties</option>{properties.map((property) => <option value={property.id} key={property.id}>{property.name}</option>)}</select></label></div><button className="button" type="submit">Save board view</button></form>
    {templates.map((template) => <details className="card" key={template.id}><summary role="button"><strong>{template.name}</strong></summary><form action={saveUnitTurnTemplateAction} className="stack" style={{ marginTop: 16 }}><Fields template={template} /></form></details>)}<details className="card"><summary role="button"><strong>Add a custom turn template</strong></summary><form action={saveUnitTurnTemplateAction} className="stack" style={{ marginTop: 16 }}><Fields /></form></details>
  </div>
}
