import Link from 'next/link'
import { redirect } from 'next/navigation'
import { prisma } from '@/lib/prisma'
import { getLandlordSession } from '@/lib/landlord-session'
import { createStaffMemberAction } from './actions'

export default async function StaffDirectoryPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const session = await getLandlordSession(); if (!session) redirect('/login?error=session-expired')
  const [staff, query] = await Promise.all([prisma.staffMember.findMany({ where: { orgId: session.userId }, include: { _count: { select: { assignedRequests: true } } }, orderBy: [{ isActive: 'desc' }, { name: 'asc' }] }), searchParams])
  return <div className="stack"><section className="row"><div><div className="kicker">In-house team</div><h1>Maintenance staff</h1><p className="muted">Manage employee access and assigned work without vendor commercial controls.</p></div><div className="row"><Link className="button" href="/staff/preferences">Assignment preferences</Link><Link className="button" href="/staff/personal-work">Personal work settings</Link></div></section>{query.error ? <div className="notice error">{query.error}</div> : null}<section className="grid cols-2"><div className="card stack"><h2>Add staff member</h2><form action={createStaffMemberAction} className="stack"><label>Name<input name="name" required /></label><label>Work email<input type="email" name="email" required /></label><label>Phone<input name="phone" /></label><label>Skills <span className="muted">(comma separated)</span><input name="skills" placeholder="Plumbing, locks, appliances" /></label><button className="button primary">Create staff account</button></form></div><div className="card stack"><h2>Current team</h2>{staff.length ? staff.map((member) => <Link href={`/staff/${member.id}`} key={member.id} className="timelineRow"><div className="row"><strong>{member.name}</strong><span className="badge">{member.isActive ? member.availabilityStatus : 'inactive'}</span></div><div className="muted">{member.email} - {member._count.assignedRequests} assigned records</div><div>{member.skillsCsv || 'No skills saved'}</div></Link>) : <div className="emptyState"><strong>No staff accounts</strong><span>Add your first in-house maintenance employee.</span></div>}</div></section></div>
}
