import { prisma } from '@/lib/prisma'
import { formatAppointmentWindow } from '@/lib/appointment-time'
import { acceptTenantAppointmentSlotAction, cancelStaffCoordinatedAppointmentAction, cancelVendorCoordinatedAppointmentAction, confirmManagerAppointmentSlotAction, proposeStaffAppointmentSlotsAction, proposeVendorAppointmentSlotsAction, requestAlternativeAppointmentSlotsAction, requestTenantAppointmentRescheduleAction, saveRequestSchedulingOverrideAction } from '@/app/scheduling/actions'

export async function AppointmentCoordinationPanel({ requestId, audience }: { requestId: string; audience: 'manager' | 'tenant' | 'vendor' | 'staff' }) {
  const request = await prisma.maintenanceRequest.findUnique({ where: { id: requestId }, include: { property: { include: { owner: true } }, appointmentProposals: { where: { status: { in: ['pending', 'selected', 'accepted'] } }, orderBy: { startAt: 'asc' } } } })
  if (!request) return null
  const enabled = request.schedulingCoordinationOverride ?? request.property.owner.schedulingCoordinationEnabled
  if (!enabled) return audience === 'manager' ? <section className="card stack"><div className="muted">Direct scheduling is disabled for this request.</div><form action={saveRequestSchedulingOverrideAction}><input type="hidden" name="requestId" value={request.id} /><button className="button" name="mode" value="enabled">Enable for this request</button></form></section> : null
  const isClosed = ['completed', 'closed', 'declined', 'canceled'].includes(request.status)
  const pending = isClosed ? [] : request.appointmentProposals.filter((proposal) => proposal.status === 'pending' && proposal.expiresAt > new Date())
  const selected = request.appointmentProposals.find((proposal) => proposal.status === 'selected')
  const accepted = request.appointmentProposals.find((proposal) => proposal.status === 'accepted')
  const canOffer = !isClosed && (audience === 'vendor' ? ['accepted', 'scheduled'].includes(request.dispatchStatus ?? '') && Boolean(request.assignedVendorId) : audience === 'staff' ? ['accepted', 'in_progress'].includes(request.staffWorkStatus ?? '') && Boolean(request.assignedStaffId) : false)
  const action = audience === 'vendor' ? proposeVendorAppointmentSlotsAction : proposeStaffAppointmentSlotsAction
  const cancelAction = audience === 'vendor' ? cancelVendorCoordinatedAppointmentAction : cancelStaffCoordinatedAppointmentAction
  return <section className="card stack" id="scheduling">
    <div className="row"><div><div className="kicker">Direct scheduling</div><h3>{accepted ? 'Appointment confirmed' : pending.length ? 'Waiting for tenant choice' : selected ? 'Waiting for manager confirmation' : 'Coordinate an appointment'}</h3></div>{audience === 'manager' ? <form action={saveRequestSchedulingOverrideAction} className="row"><input type="hidden" name="requestId" value={request.id} /><select name="mode" defaultValue={request.schedulingCoordinationOverride === true ? 'enabled' : request.schedulingCoordinationOverride === false ? 'disabled' : 'default'} aria-label="Direct scheduling setting"><option value="default">Use portfolio default</option><option value="enabled">Enabled for this request</option><option value="disabled">Disabled for this request</option></select><button className="button">Save</button></form> : null}</div>
    {accepted ? <div className="notice success">{formatAppointmentWindow(accepted.startAt, accepted.endAt)} with {accepted.proposedByName}</div> : null}
    {accepted && !isClosed && audience === 'tenant' ? <form action={requestTenantAppointmentRescheduleAction} className="stack"><input type="hidden" name="requestId" value={request.id} /><label>Need another time?<textarea name="reason" rows={2} placeholder="Explain what timing would work better" required /></label><button className="button">Request another time</button></form> : null}
    {accepted && !isClosed && (audience === 'vendor' || audience === 'staff') ? <form action={cancelAction} className="stack"><input type="hidden" name="requestId" value={request.id} /><label>Cancellation reason<textarea name="reason" rows={2} required /></label><button className="button">Cancel appointment and offer new times</button></form> : null}
    {audience === 'tenant' && pending.length ? <div className="stack"><p>Choose the appointment time that works for you.</p>{pending.map((proposal) => <form action={acceptTenantAppointmentSlotAction} className="timelineRow row" key={proposal.id}><input type="hidden" name="requestId" value={request.id} /><input type="hidden" name="proposalId" value={proposal.id} /><div style={{ flex: 1 }}><strong>{formatAppointmentWindow(proposal.startAt, proposal.endAt)}</strong><div className="muted">Offered by {proposal.proposedByName}{proposal.note ? ` - ${proposal.note}` : ''}</div></div><button className="button primary">Choose this time</button></form>)}<form action={requestAlternativeAppointmentSlotsAction} className="stack"><input type="hidden" name="requestId" value={request.id} /><label>None of these work?<textarea name="reason" rows={2} placeholder="Share days or times that work better" required /></label><button className="button">Ask for different times</button></form></div> : null}
    {audience === 'manager' && selected ? <form action={confirmManagerAppointmentSlotAction} className="notice row"><input type="hidden" name="requestId" value={request.id} /><input type="hidden" name="proposalId" value={selected.id} /><div style={{ flex: 1 }}><strong>Tenant selected {formatAppointmentWindow(selected.startAt, selected.endAt)}</strong><div className="muted">Confirm to add it to the maintenance calendar.</div></div><button className="button primary">Confirm appointment</button></form> : null}
    {(audience === 'manager' || audience === 'vendor' || audience === 'staff') && pending.length ? <div className="stack"><strong>Offered times</strong>{pending.map((proposal) => <div className="timelineRow" key={proposal.id}>{formatAppointmentWindow(proposal.startAt, proposal.endAt)}<div className="muted">{proposal.proposedByName}</div></div>)}</div> : null}
    {canOffer && !accepted ? <form action={action} className="stack"><input type="hidden" name="requestId" value={request.id} /><p className="muted">Offer up to three choices. Times must be between {request.property.owner.schedulingWorkingHourStart}:00 and {request.property.owner.schedulingWorkingHourEnd}:00 with {request.property.owner.schedulingMinimumNoticeHours} hours notice.</p>{[1, 2, 3].map((slot) => <div className="grid cols-2" key={slot}><label>Choice {slot} starts<input type="datetime-local" name="slotStart" required={slot === 1} /></label><label>Choice {slot} ends<input type="datetime-local" name="slotEnd" required={slot === 1} /></label></div>)}<label>Note for tenant<textarea name="note" rows={2} placeholder="Access instructions or timing notes" /></label><button className="button primary">Send appointment choices</button></form> : null}
    {audience === 'tenant' && !pending.length && !accepted ? <div className="muted">No appointment choices are waiting for you.</div> : null}
  </section>
}
