import Link from 'next/link'

export function TermsContent() {
  return (
    <div className="stack legalDocument">
      <p>These Terms of Service ("Terms") are a binding agreement between Simeonware LLC, an Arizona limited liability company ("Simeonware," "we," "us," or "our"), and each person or organization that accesses or uses Simeonware Maintenance Manager, our websites, mobile experiences, communications, integrations, and related services (collectively, the "Service"). "Customer" means the property-management business or other organization that creates or pays for a manager account. "Authorized User" means a manager, tenant, resident, maintenance staff member, vendor, board participant, or other person permitted to use the Service through a Customer. "You" means the Customer or Authorized User, as applicable.</p>
      <h3>Agreement, authority, and eligibility</h3>
      <p>By creating an account, accepting an invitation, checking an acceptance box, purchasing a subscription, or using the Service, you agree to these Terms and acknowledge the Privacy Policy. If you use the Service for an organization, you represent that you have authority to bind that organization. You must be legally capable of entering into this agreement and may use the Service only for lawful, authorized property-maintenance activity. A Customer is responsible for its Authorized Users and for identifying the persons authorized to administer its account.</p>
      <h3>The Service and allocation of responsibility</h3>
      <p>Simeonware supplies workflow, coordination, communication, scheduling, recordkeeping, inspection, billing-support, and integration tools. Simeonware is not a property manager, landlord, repair contractor, emergency service, insurer, fiduciary, payment processor, law firm, accounting firm, or tax adviser. The Customer remains solely responsible for the condition and operation of its properties; emergency response; legal and regulatory compliance; habitability and safety duties; inspections; vendor and employee selection and supervision; board and resident approvals; repair decisions; notices; payments; chargebacks; accounting treatment; and review of all records, recommendations, messages, automations, and integration results.</p>
      <h3>No emergency or life-safety reliance</h3>
      <p>The Service must not be used as the sole method for reporting, monitoring, or responding to fire, gas, electrical, structural, flooding, sewage, security, medical, or other emergencies. Users must contact local emergency services and the responsible property representative when immediate action may be required. Notifications can be delayed, filtered, rejected, misdirected, or unavailable. Simeonware does not guarantee that any person will receive, read, understand, or act on a request or notification within a particular time.</p>
      <h3>Accounts, administrators, and credentials</h3>
      <p>The Customer controls its organization, properties, units, invitations, permissions, integrations, subscription, and operational records. You must provide accurate information, invite only authorized persons, use reasonable account-security practices, protect credentials and access links, promptly remove access that is no longer authorized, and immediately report suspected misuse or compromise. Actions taken through valid credentials, access links, or an authorized integration may be treated as authorized until Simeonware receives and can reasonably act on notice to the contrary.</p>
      <h3>Trials and subscriptions</h3>
      <p>A trial begins when the property-manager account is created and lasts for the period displayed during signup. No card is required and a trial does not automatically become paid service. Continued access after a trial requires a separate paid checkout where the exact price, frequency, renewal terms, and cancellation method are shown and affirmatively accepted.</p>
      <p>Paid subscriptions renew at the selected monthly or annual interval until canceled. Online subscribers may cancel online before the next renewal to prevent the next charge. Cancellation normally takes effect at the end of the paid period, and prior charges are nonrefundable except where required by law or expressly stated otherwise.</p>
      <h3>Fees and taxes</h3>
      <p>Subscription charges are shown in U.S. dollars at checkout unless another currency is expressly displayed. The Customer is responsible for applicable taxes, valid billing information, authorized purchases, and charges resulting from approved plans, capacity, or separately accepted services. Unit-capacity changes and plan changes affect charges only as disclosed in the applicable workflow. Except where law requires otherwise, fees already paid are not refundable or creditable for partial periods, unused capacity, account suspension caused by a violation, or a Customer-requested deletion.</p>
      <h3>Customer content and legal authority</h3>
      <p>"Customer Content" includes property, unit, tenant, resident, staff, vendor, board, maintenance, message, photo, video, document, inspection, scheduling, financial, integration, and other information submitted to or generated through the Service for a Customer. As between the parties, the Customer retains its rights in Customer Content. The Customer grants Simeonware and its service providers a nonexclusive, worldwide, royalty-free license to host, copy, process, transmit, display, adapt, and otherwise use Customer Content only as reasonably necessary to operate, secure, support, troubleshoot, and improve the Service, comply with law, and enforce these Terms.</p>
      <p>You represent that you have all permissions, notices, consents, and lawful bases required to provide Customer Content and allow its processing. You must not submit information you are prohibited from collecting or sharing. The Customer is responsible for responding to requests from its tenants, residents, employees, vendors, and other data subjects unless applicable law assigns that responsibility to Simeonware.</p>
      <h3>Accuracy, imports, and automated actions</h3>
      <p>You must review imported, translated, synchronized, calculated, summarized, or automatically generated information for completeness, accuracy, duplication, and proper accounting or operational treatment before relying on it. Source data, user entries, translations, integrations, and third-party systems may be incomplete, delayed, duplicated, or incorrect. Simeonware does not warrant that a category, urgency, recommendation, status, calendar entry, amount, chargeback, invoice, export, translation, or synchronization is accurate or legally sufficient.</p>
      <h3>Customer records and independent copies</h3>
      <p>The Service is a maintenance-coordination tool and is not the Customer's exclusive accounting ledger, statutory record repository, evidence archive, emergency log, or business-continuity system. The Customer must maintain independent, current copies of records that are legally required, financially material, operationally critical, irreplaceable, or needed to continue property operations without the Service. Available exports are a convenience and do not transfer this responsibility to Simeonware.</p>
      <h3>Security, backups, and risk of data loss</h3>
      <p>Simeonware uses reasonable technical and organizational safeguards appropriate to the nature of the Service and maintains operational backup and recovery procedures. No online service, storage system, transmission method, security control, or recovery process is completely secure, uninterrupted, or error-free. Customer Content may be lost, corrupted, altered, delayed, duplicated, rendered unavailable, or disclosed because of software defects, user action, credential compromise, malicious activity, provider failure, integration behavior, legal process, disaster, or events outside reasonable control.</p>
      <p>Operational backups are maintained for disaster recovery and are not a customer-controlled archive, version history, or guaranteed restoration service. Simeonware does not promise that every item, attachment, message, transaction, or recent change can be restored, or that restoration will return the Service to an exact point in time. A workspace reset, account deletion, authorized deletion, retention expiration, or third-party deletion may be irreversible in the active Service. To the maximum extent permitted by law, Simeonware is not responsible for loss or corruption of Customer Content, loss of access, or the cost of reconstructing records, except to the extent caused by liability that cannot lawfully be excluded and always subject to the limitations below.</p>
      <h3>Connected services</h3>
      <p>Optional Stripe, mailbox, calendar, QuickBooks, storage, translation, notification, app-store, and other third-party services are governed by their providers' terms and practices. You authorize the data access and actions you enable. Simeonware does not control and is not responsible for a third party's availability, security, pricing, changes, errors, data handling, or decisions. A third-party outage or change may impair an integration without entitling the Customer to a refund. Simeonware does not mark a vendor bill paid unless the connected accounting provider confirms payment or an authorized manager records payment through an available workflow.</p>
      <h3>Electronic communications</h3>
      <p>You consent to receive account, security, legal, workflow, trial, billing, and service communications electronically at the addresses or devices associated with your account. You are responsible for keeping contact information current and configuring spam filters, allowlists, devices, and carrier settings. Marketing communications, where used, remain subject to applicable consent and opt-out requirements.</p>
      <h3>Acceptable use</h3>
      <p>You may not access another organization without authorization; share restricted access links; probe, scan, bypass, or defeat security or rate limits; reverse engineer except where law expressly permits; interfere with the Service; introduce malware; scrape or use automated access without written permission; upload unlawful, infringing, deceptive, discriminatory, abusive, or harmful material; misuse personal information; impersonate another person; misrepresent maintenance, inspection, approval, invoice, charge, or payment activity; use the Service for surveillance or unlawful screening; or violate law or another person's rights. You may not use the Service to make fully automated decisions that produce legal or similarly significant effects on individuals unless independently authorized and compliant with applicable law.</p>
      <h3>Simeonware ownership and feedback</h3>
      <p>Simeonware and its licensors retain all rights in the Service, software, workflows, interfaces, documentation, branding, aggregate usage information, and improvements. Subject to these Terms and payment of applicable fees, Simeonware grants the Customer a limited, revocable, nonexclusive, nontransferable right for its Authorized Users to use the Service during the applicable subscription or trial. If you provide suggestions or feedback, you grant Simeonware a perpetual, irrevocable, worldwide, royalty-free right to use it without restriction or compensation, provided Simeonware does not publicly identify you as its source without permission.</p>
      <h3>Service changes, previews, and availability</h3>
      <p>Simeonware may maintain, modify, replace, limit, or discontinue features to improve security, reliability, compliance, or the Service. We will use reasonable efforts to avoid materially reducing paid core functionality during a current paid term without notice, but no particular integration or third-party-dependent feature is guaranteed. Preview, beta, or experimental features may be changed or withdrawn at any time and are provided for evaluation with greater risk of errors or data loss.</p>
      <h3>Suspension</h3>
      <p>Simeonware may immediately restrict or suspend access when reasonably necessary to address a security risk, protect people or property, prevent unlawful or abusive use, respond to legal process, protect another customer, contain excessive resource use, investigate suspected fraud, or address a material breach of these Terms. Where practical and lawful, we will provide notice and an opportunity to cure. Suspension does not excuse accrued payment obligations.</p>
      <h3>Termination, export, deletion, and retention</h3>
      <p>A Customer may cancel a subscription or request deletion through available account workflows. The Customer is responsible for exporting needed records before access ends or deletion becomes effective. Following termination or deletion, Simeonware may delete or de-identify Customer Content from active systems and retain limited records when required or reasonably necessary for legal, accounting, fraud-prevention, security, dispute, and backup purposes. Disaster-recovery copies may persist until overwritten or expired under the backup schedule and are not restored to active use except for legitimate recovery, security, or legal needs. Simeonware has no obligation to preserve or return Customer Content after the applicable access or retention period unless law requires otherwise.</p>
      <h3>Disclaimer of warranties</h3>
      <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE." SIMEONWARE DISCLAIMS ALL EXPRESS, IMPLIED, STATUTORY, AND OTHER WARRANTIES, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, QUIET ENJOYMENT, ACCURACY, SECURITY, AVAILABILITY, AND RESULTS. SIMEONWARE DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, LOSS-FREE, COMPLETELY SECURE, OR COMPATIBLE WITH EVERY DEVICE OR THIRD-PARTY SYSTEM; THAT DEFECTS OR LOST DATA WILL BE CORRECTED OR RESTORED; OR THAT ANY VENDOR, STAFF MEMBER, TENANT, RESIDENT, BOARD MEMBER, INTEGRATION, OR OTHER USER WILL PERFORM AS EXPECTED.</p>
      <h3>Exclusion of certain damages</h3>
      <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, SIMEONWARE AND ITS MEMBERS, MANAGERS, EMPLOYEES, CONTRACTORS, LICENSORS, AND SERVICE PROVIDERS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES; LOST PROFITS, REVENUE, SAVINGS, BUSINESS, GOODWILL, OR OPPORTUNITY; BUSINESS INTERRUPTION; SUBSTITUTE SERVICES; LOSS, CORRUPTION, DISCLOSURE, OR RECONSTRUCTION OF DATA; PROPERTY-MANAGEMENT, REPAIR, REHOUSING, PENALTY, FINE, CHARGEBACK, OR THIRD-PARTY COSTS; OR DAMAGES ARISING FROM EMERGENCY RESPONSE, VENDOR WORKMANSHIP, USER DECISIONS, THIRD-PARTY SERVICES, OR UNAUTHORIZED ACCESS, EVEN IF ADVISED THAT SUCH LOSS WAS POSSIBLE AND REGARDLESS OF THE THEORY OF LIABILITY.</p>
      <h3>Aggregate liability cap</h3>
      <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE TOTAL AGGREGATE LIABILITY OF SIMEONWARE AND THE PARTIES LISTED ABOVE FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THE SERVICE OR THESE TERMS WILL NOT EXCEED THE GREATER OF (A) THE FEES PAID OR PAYABLE BY THE CUSTOMER TO SIMEONWARE FOR THE SERVICE DURING THE 12 MONTHS IMMEDIATELY BEFORE THE EVENT GIVING RISE TO THE FIRST CLAIM, OR (B) US $100. MULTIPLE CLAIMS DO NOT INCREASE THIS CAP. THE DISCLAIMERS, EXCLUSIONS, AND CAP ARE ESSENTIAL PARTS OF THE AGREEMENT AND APPLY EVEN IF A REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</p>
      <h3>Liability that cannot be excluded</h3>
      <p>Nothing in these Terms excludes or limits liability for fraud or fraudulent misrepresentation; willful misconduct; death or personal injury caused by negligence where such liability cannot be limited; or any warranty, remedy, privacy obligation, data-protection responsibility, consumer guarantee, or other right or liability that applicable law does not permit the parties to exclude or limit. Each disclaimer, exclusion, and limitation applies only to the maximum extent permitted by the law governing the particular claim.</p>
      <h3>Country-specific mandatory rights</h3>
      <p>For a consumer in the United Kingdom, these Terms do not exclude the statutory requirement to perform services with reasonable care and skill or limit applicable liability below the amount permitted by the Consumer Rights Act 2015. For a consumer in Australia, the Service comes with guarantees that cannot be excluded under the Australian Consumer Law; where lawful for services not ordinarily acquired for personal, domestic, or household use, Simeonware's liability for failure to comply with a consumer guarantee is limited to supplying the services again or paying the cost of having them supplied again. Canadian privacy and safeguarding obligations, including nonwaivable obligations applicable under PIPEDA or provincial law, are not displaced by these Terms. This section prevails over an inconsistent limitation only to the extent required by applicable law.</p>
      <h3>Customer indemnity</h3>
      <p>To the maximum extent permitted by law, the Customer will defend, indemnify, and hold harmless Simeonware and its members, managers, employees, and contractors from third-party claims, damages, penalties, judgments, settlements, and reasonable legal fees arising from Customer Content; the Customer's properties or property-management activity; an Authorized User's use of the Service; unlawful or unauthorized collection, disclosure, instruction, invitation, charge, approval, or communication; a vendor's or employee's work; or the Customer's breach of these Terms or applicable law. Simeonware will provide prompt notice where reasonably practicable, permit the Customer to control the defense with qualified counsel, and may participate at its own expense. The Customer may not settle a claim in a manner that admits fault by or imposes an obligation on Simeonware without Simeonware's written consent.</p>
      <h3>Force majeure</h3>
      <p>Simeonware is not responsible for delay or failure caused by events beyond its reasonable control, including natural disaster, severe weather, fire, epidemic, war, terrorism, civil disorder, labor disruption, utility or telecommunications failure, internet routing failure, cyberattack, governmental action, legal process, provider outage, app-store action, or failure of third-party infrastructure. This section does not excuse payment obligations already incurred.</p>
      <h3>Governing law</h3>
      <p>These Terms are governed by Arizona law, without regard to conflict-of-law rules. Any dispute that may lawfully be restricted to a forum must be brought exclusively in a state or federal court serving Maricopa County, Arizona, and each party consents to personal jurisdiction there. This provision does not remove nonwaivable rights, forums, or remedies available under another applicable law.</p>
      <h3>Assignment, relationship, and third parties</h3>
      <p>The Customer may not assign these Terms or transfer its account without Simeonware's written consent. Simeonware may assign these Terms in connection with a merger, financing, reorganization, sale of assets, or transfer of the Service. The parties are independent contractors. These Terms do not create an agency, partnership, joint venture, employment, fiduciary, franchise, or beneficiary relationship. Except for the Simeonware parties expressly protected by the disclaimers, limitations, and indemnity, there are no third-party beneficiaries.</p>
      <h3>Entire agreement, order, and interpretation</h3>
      <p>These Terms, the Privacy Policy, an applicable assisted-trial agreement, and terms affirmatively accepted at paid checkout form the entire agreement concerning the Service and replace prior discussions on the same subject. Checkout terms control only for price, plan, billing frequency, and renewal where they conflict with these Terms. Headings are for convenience. "Including" means "including without limitation." An electronic record and electronic acceptance have the same effect as a signed paper agreement.</p>
      <h3>Severability, waiver, and survival</h3>
      <p>If a provision is found unenforceable, it will be enforced to the maximum lawful extent and the remaining provisions continue. A failure or delay in enforcement is not a waiver. Provisions concerning fees, ownership, Customer Content licenses needed for winding down or legal compliance, deletion and retention, disclaimers, liability, indemnity, disputes, and interpretation survive termination to the extent their nature requires.</p>
      <h3>Changes and contact</h3>
      <p>Simeonware may update these Terms to reflect changes in the Service, law, security, providers, or business practices. Material changes will be communicated through the Service or by email and may require renewed acceptance before continued use. Changes apply prospectively from the stated effective date unless law requires otherwise. Legal notices and questions may be sent to <a href="mailto:support@simeonware.com">support@simeonware.com</a>.</p>
    </div>
  )
}

export function PrivacyContent() {
  return (
    <div className="stack legalDocument">
      <p>Simeonware collects account details, contact information, property and unit records, tenant and vendor details, requests, messages, photos, files, schedules, inspections, billing records, integration data, device identifiers, and security and audit events needed to operate the service.</p>
      <h3>How information is used</h3>
      <p>Information is used to authenticate users, coordinate maintenance, send notifications, operate requested integrations, process subscriptions, provide support, prevent abuse, investigate incidents, maintain records, and improve reliability.</p>
      <h3>Sharing</h3>
      <p>Simeonware does not sell personal information. Information is shared with authorized participants in a maintenance workflow and with providers that supply hosting, databases, private storage, email, authentication, monitoring, payment, calendar, mailbox, accounting, and similar operating services.</p>
      <h3>Retention and security</h3>
      <p>Records are retained while needed to operate accounts and for legitimate legal, accounting, security, dispute, and backup purposes. Reasonable technical and organizational safeguards are used, but no system can guarantee absolute security.</p>
      <h3>Your choices</h3>
      <p>Authorized users may correct information through available account workflows. Property managers can disconnect optional integrations, request a 24-hour workspace reset that preserves the account and subscription while removing operational portfolio data, or request full account deletion. Some records may be retained where required or reasonably necessary for legal, accounting, fraud-prevention, security, or short-term disaster-recovery purposes.</p>
      <h3>Contact</h3>
      <p>Privacy questions and requests may be sent to <a href="mailto:support@simeonware.com">support@simeonware.com</a>. The complete policy remains available at <Link href="/privacy">simeonware.com/privacy</Link>.</p>
    </div>
  )
}

export function AssistedTrialContent() {
  return (
    <div className="stack legalDocument">
      <p>The 30-Day Assisted Trial is available by invitation to businesses managing property in the 50 United States or District of Columbia. One trial is normally available per business or related business group.</p>
      <h3>Start and expiration</h3>
      <p>The trial starts immediately when the invited property-manager account is successfully created and ends 30 consecutive days later at the date and time shown in the account. Consultation or import scheduling does not delay or extend the trial. Any extension must be approved in writing by Simeonware.</p>
      <h3>No automatic charge</h3>
      <p>No payment method is required. Selecting an intended plan does not authorize a charge, and the trial does not automatically convert to paid service. Continuing after expiration requires a separate paid checkout and express payment authorization.</p>
      <h3>Included assistance</h3>
      <p>The trial includes one complimentary onboarding consultation, subject to mutually available scheduling, and reasonable assistance importing supported property, unit, tenant, staff, and vendor records identified during onboarding. Simeonware will normally offer consultation times within a few business days.</p>
      <h3>Customer review</h3>
      <p>The customer must provide authorized, complete source information and review all imported records. Assistance does not include reconstructing missing records, correcting unrelated source-system errors, or guaranteeing compatibility with every format.</p>
      <h3>Selected plan and price protection</h3>
      <p>The customer selects an intended plan and billing frequency during signup, but that selection is not a payment authorization. If the customer purchases the selected service before the trial expires, the base subscription price and additional-unit rate shown for that purchase will remain unchanged for 12 months from the first paid subscription date. Taxes, customer-requested plan changes, added capacity, and separately approved services are excluded.</p>
      <h3>Reminders and expiration</h3>
      <p>Simeonware sends trial-ending reminders approximately seven and two days before expiration. If no paid subscription is purchased, subscription-controlled manager access is paused and no charge is made. Information remains subject to the Terms of Service and Privacy Policy.</p>
      <h3>No guaranteed results</h3>
      <p>The trial does not guarantee savings, vendor performance, tenant satisfaction, compliance, or a particular maintenance outcome.</p>
    </div>
  )
}
