import { prisma } from '@/lib/prisma'
import { getLandlordSession } from '@/lib/landlord-session'
import { calculatePersonalWorkCharge } from '@/lib/personal-work'
import { createPersonalWorkInvoiceAction, reviewPersonalWorkAction } from '@/app/staff/personal-work/request-actions'

export async function PersonalWorkPanel({ requestId }: { requestId: string }) {
  const session = await getLandlordSession(); if (!session) return null
  const request = await prisma.maintenanceRequest.findFirst({ where: { id: requestId, property: { ownerId: session.userId }, workResponsibility: 'tenant_personal_work' }, include: { staffWorkLogs: true } }); if (!request) return null
  const charge = calculatePersonalWorkCharge({ laborMinutes: request.staffWorkLogs.map((log) => log.laborMinutes), materialsCents: request.staffWorkLogs.map((log) => log.materialsCents), hourlyRateCents: request.personalWorkHourlyRateCents ?? 0, minimumMinutes: request.personalWorkMinimumMinutes ?? 0, authorizedMaxCents: request.personalWorkAuthorizedMaxCents ?? 0 })
  return <section className="card stack"><div><div className="kicker">Tenant-paid personal work</div><h3>{request.personalWorkStatus?.replaceAll('_', ' ') ?? 'requested'}</h3></div><div className="grid cols-3"><div><strong>${((request.personalWorkHourlyRateCents ?? 0) / 100).toFixed(2)}/hour</strong><div className="muted">Saved rate</div></div><div><strong>{request.personalWorkMinimumMinutes ?? 0} minutes</strong><div className="muted">Minimum labor</div></div><div><strong>${((request.personalWorkAuthorizedMaxCents ?? 0) / 100).toFixed(2)}</strong><div className="muted">Tenant authorization</div></div></div>{request.personalWorkStatus === 'requested' ? <div className="row"><form action={reviewPersonalWorkAction}><input type="hidden" name="requestId" value={request.id} /><button className="button primary" name="decision" value="approved">Approve personal work</button></form><form action={reviewPersonalWorkAction}><input type="hidden" name="requestId" value={request.id} /><button className="button" name="decision" value="declined">Decline</button></form></div> : null}{request.personalWorkStatus === 'completed_pending_review' ? <form action={createPersonalWorkInvoiceAction} className="stack"><div className="notice">Staff recorded ${(charge.laborCents / 100).toFixed(2)} labor and ${(charge.materialsCents / 100).toFixed(2)} materials.{charge.exceedsAuthorization ? ' The total exceeds the tenant authorization and is capped.' : ''}</div><input type="hidden" name="requestId" value={request.id} /><label>Final tenant invoice ($)<input name="invoiceAmount" type="number" min="0" max={(charge.invoiceCents / 100).toFixed(2)} step="0.01" defaultValue={(charge.invoiceCents / 100).toFixed(2)} required /></label><button className="button primary">Create tenant invoice</button></form> : null}</section>
}
