import type { MaintenanceRequest, Property, RequestComment, StatusEvent, Unit, Vendor } from '@/lib/types'

export const properties: Property[] = [
  { id: 'prop-1', name: 'Canyon View Duplex', address: '742 W Mesquite Ave, Phoenix, AZ', isActive: true, unitCount: 2 },
  { id: 'prop-2', name: 'Palm Court Fourplex', address: '1810 N 14th St, Phoenix, AZ', isActive: true, unitCount: 4 },
]

export const units: Unit[] = [
  // Canyon View Duplex
  { id: 'unit-1a', propertyId: 'prop-1', label: 'Unit A', tenantName: 'Taylor Reed',  tenantEmail: 'taylor@example.com', isActive: true },
  { id: 'unit-1b', propertyId: 'prop-1', label: 'Unit B', tenantName: 'Jordan Hayes', tenantEmail: 'jordan@example.com', isActive: true },
  // Palm Court Fourplex
  { id: 'unit-2a', propertyId: 'prop-2', label: 'Unit 1', tenantName: 'Maria Soto',   tenantEmail: 'maria@example.com', isActive: true },
  { id: 'unit-2b', propertyId: 'prop-2', label: 'Unit 2', tenantName: 'Dev Patel',    tenantEmail: 'dev@example.com', isActive: true },
  { id: 'unit-2c', propertyId: 'prop-2', label: 'Unit 3', tenantName: 'Chris Ortiz',  tenantEmail: 'chris@example.com', isActive: true },
  { id: 'unit-2d', propertyId: 'prop-2', label: 'Unit 4', isActive: true },
]

const withBaseRequest = (request: Omit<MaintenanceRequest, 'triageTags'>): MaintenanceRequest => ({
  ...request,
  triageTags: [],
})

export const requests: MaintenanceRequest[] = [
  withBaseRequest({
    id: 'req-1001',
    propertyId: 'prop-1',
    unitId: 'unit-1a',
    submittedByName: 'Taylor Reed',
    submittedByEmail: 'taylor@example.com',
    preferredCurrency: 'usd',
    preferredLanguage: 'english',
    title: 'Kitchen sink leaking under cabinet',
    description: 'Active drip under the kitchen sink — base panel is already warped. Needs a plumber soon.',
    category: 'Plumbing',
    urgency: 'high',
    status: 'new',
    createdAt: '2026-03-11T17:30:00Z',
  }),
  withBaseRequest({
    id: 'req-1002',
    propertyId: 'prop-2',
    unitId: 'unit-2c',
    submittedByName: 'Chris Ortiz',
    submittedByEmail: 'chris@example.com',
    preferredCurrency: 'peso',
    preferredLanguage: 'spanish',
    title: 'Bedroom AC vent not cooling',
    description: 'Airflow is weak in the back bedroom even with thermostat set to 68°. Rest of the unit is fine.',
    category: 'HVAC',
    urgency: 'medium',
    status: 'scheduled',
    assignedVendorName: 'Desert Air Service',
    assignedVendorEmail: 'dispatch@desertair.example.com',
    assignedVendorPhone: '602-555-0112',
    createdAt: '2026-03-10T20:00:00Z',
  }),
  withBaseRequest({
    id: 'req-1003',
    propertyId: 'prop-1',
    unitId: 'unit-1b',
    submittedByName: 'Jordan Hayes',
    submittedByEmail: 'jordan@example.com',
    preferredCurrency: 'pound',
    preferredLanguage: 'french',
    title: 'Exterior gate latch broken',
    description: 'Side gate does not latch after closing. Security concern — anyone can push it open.',
    category: 'Exterior',
    urgency: 'low',
    status: 'done',
    assignedVendorName: 'Mesa Repair Co.',
    assignedVendorEmail: 'service@mesarepair.example.com',
    assignedVendorPhone: '480-555-0177',
    createdAt: '2026-02-28T14:15:00Z',
  }),
  withBaseRequest({
    id: 'req-1004',
    propertyId: 'prop-2',
    unitId: 'unit-2a',
    submittedByName: 'Maria Soto',
    submittedByEmail: 'maria@example.com',
    preferredCurrency: 'euro',
    preferredLanguage: 'english',
    title: 'Bathroom faucet slow drip — hot side',
    description: 'Hot water faucet in the main bathroom drips constantly when off. Running up the water bill.',
    category: 'Plumbing',
    urgency: 'medium',
    status: 'in_progress',
    assignedVendorName: 'Southwest Plumbing',
    assignedVendorEmail: 'dispatch@southwestplumbing.example.com',
    assignedVendorPhone: '623-555-0144',
    createdAt: '2026-03-15T09:00:00Z',
  }),
  withBaseRequest({
    id: 'req-1005',
    propertyId: 'prop-1',
    unitId: 'unit-1a',
    submittedByName: 'Taylor Reed',
    submittedByEmail: 'taylor@example.com',
    preferredCurrency: 'usd',
    preferredLanguage: 'spanish',
    title: 'Kitchen drain backing up',
    description: 'Kitchen drain is draining very slowly. Possibly related to the earlier sink issue — or a separate clog.',
    category: 'Plumbing',
    urgency: 'low',
    status: 'new',
    createdAt: '2026-03-20T11:45:00Z',
  }),
]

export const vendors: Vendor[] = [
  {
    id: 'vendor-1',
    orgId: 'seed-org',
    name: 'Southwest Plumbing',
    email: 'dispatch@southwestplumbing.example.com',
    phone: '623-555-0144',
    categories: ['Plumbing'],
    supportedLanguages: ['english', 'spanish'],
    supportedCurrencies: ['usd', 'peso'],
    isActive: true,
  },
  {
    id: 'vendor-2',
    orgId: 'seed-org',
    name: 'Desert Air Service',
    email: 'dispatch@desertair.example.com',
    phone: '602-555-0112',
    categories: ['HVAC'],
    supportedLanguages: ['english', 'spanish'],
    supportedCurrencies: ['usd', 'peso'],
    isActive: true,
  },
  {
    id: 'vendor-3',
    orgId: 'seed-org',
    name: 'Mesa Repair Co.',
    email: 'service@mesarepair.example.com',
    phone: '480-555-0177',
    categories: ['Exterior'],
    supportedLanguages: ['english', 'french'],
    supportedCurrencies: ['usd', 'pound', 'euro'],
    isActive: true,
  },
]

export const requestComments: RequestComment[] = [
  {
    id: 'comment-1',
    requestId: 'req-1001',
    authorName: 'Taylor Reed',
    body: 'Leak started this morning and is dripping every few seconds. Already put a bucket under it.',
    visibility: 'external',
    createdAt: '2026-03-11T17:31:00Z',
  },
  {
    id: 'comment-2',
    requestId: 'req-1001',
    authorName: 'Elon PM Ops',
    body: 'Reaching out to plumber. Will confirm appointment window by end of day.',
    visibility: 'internal',
    createdAt: '2026-03-12T09:15:00Z',
  },
  {
    id: 'comment-3',
    requestId: 'req-1002',
    authorName: 'Elon PM Ops',
    body: 'Vendor scheduled for Thursday between 9 and 11 AM. Confirmed with Desert Air Service.',
    visibility: 'external',
    createdAt: '2026-03-10T20:20:00Z',
  },
  {
    id: 'comment-4',
    requestId: 'req-1003',
    authorName: 'Elon PM Ops',
    body: 'Latch replacement approved. Vendor completed work on 3/10 — gate latches securely now.',
    visibility: 'external',
    createdAt: '2026-03-10T16:00:00Z',
  },
  {
    id: 'comment-5',
    requestId: 'req-1004',
    authorName: 'Elon PM Ops',
    body: 'Southwest Plumbing confirmed for tomorrow morning. Will replace the cartridge.',
    visibility: 'external',
    createdAt: '2026-03-16T10:30:00Z',
  },
  {
    id: 'comment-6',
    requestId: 'req-1005',
    authorName: 'Elon PM Ops',
    body: 'This is the second plumbing issue for Unit A in the past two weeks. Will scope both together.',
    visibility: 'internal',
    createdAt: '2026-03-20T14:00:00Z',
  },
]

export const statusEvents: StatusEvent[] = [
  {
    id: 'event-1',
    requestId: 'req-1001',
    toStatus: 'new',
    actorName: 'System',
    createdAt: '2026-03-11T17:30:00Z',
  },
  {
    id: 'event-2',
    requestId: 'req-1002',
    toStatus: 'new',
    actorName: 'System',
    createdAt: '2026-03-10T20:00:00Z',
  },
  {
    id: 'event-3',
    requestId: 'req-1002',
    fromStatus: 'new',
    toStatus: 'scheduled',
    actorName: 'Elon PM Ops',
    createdAt: '2026-03-10T20:15:00Z',
  },
  {
    id: 'event-4',
    requestId: 'req-1003',
    toStatus: 'new',
    actorName: 'System',
    createdAt: '2026-02-28T14:15:00Z',
  },
  {
    id: 'event-5',
    requestId: 'req-1003',
    fromStatus: 'new',
    toStatus: 'scheduled',
    actorName: 'Elon PM Ops',
    createdAt: '2026-03-05T11:00:00Z',
  },
  {
    id: 'event-6',
    requestId: 'req-1003',
    fromStatus: 'scheduled',
    toStatus: 'in_progress',
    actorName: 'Elon PM Ops',
    createdAt: '2026-03-10T08:30:00Z',
  },
  {
    id: 'event-7',
    requestId: 'req-1003',
    fromStatus: 'in_progress',
    toStatus: 'done',
    actorName: 'Elon PM Ops',
    createdAt: '2026-03-10T15:45:00Z',
  },
  {
    id: 'event-8',
    requestId: 'req-1004',
    toStatus: 'new',
    actorName: 'System',
    createdAt: '2026-03-15T09:00:00Z',
  },
  {
    id: 'event-9',
    requestId: 'req-1004',
    fromStatus: 'new',
    toStatus: 'in_progress',
    actorName: 'Elon PM Ops',
    createdAt: '2026-03-16T08:00:00Z',
  },
  {
    id: 'event-10',
    requestId: 'req-1005',
    toStatus: 'new',
    actorName: 'System',
    createdAt: '2026-03-20T11:45:00Z',
  },
]
